import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'features/auth/screens/login_screen.dart';
import 'features/auth/screens/start_page.dart';
import 'features/dashboard/screens/main_navigation.dart';
import 'shared/theme/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  // Note: In production, use firebase_options.dart generated by FlutterFire CLI
  // For now, you'll need to configure Firebase manually or use FlutterFire CLI:
  // flutter pub global activate flutterfire_cli
  // flutterfire configure
  try {
    await Firebase.initializeApp();
  } catch (e) {
    // Handle Firebase initialization error
    debugPrint('Firebase initialization error: $e');
    debugPrint('Please configure Firebase before running the app');
  }
  
  runApp(const ProviderScope(child: StudyMateApp()));
}

class StudyMateApp extends StatelessWidget {
  const StudyMateApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'StudyMate',
      theme: AppTheme.lightTheme,
      debugShowCheckedModeBanner: false,
      home: const StartPage(),
    );
  }
}

class AuthWrapper extends ConsumerWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
        if (snapshot.hasData) {
          return const MainNavigation();
        }
        return const LoginScreen();
      },
    );
  }
}
